# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aboba.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 380, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(230, 10, 541, 91))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(26)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.InfoBox = QtWidgets.QLabel(self.centralwidget)
        self.InfoBox.setGeometry(QtCore.QRect(290, 170, 661, 341))
        self.InfoBox.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.InfoBox.setObjectName("InfoBox")
        self.WordInput = QtWidgets.QLabel(self.centralwidget)
        self.WordInput.setGeometry(QtCore.QRect(80, 300, 161, 61))
        self.WordInput.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.WordInput.setText("")
        self.WordInput.setObjectName("WordInput")
        self.Me = QtWidgets.QLabel(self.centralwidget)
        self.Me.setGeometry(QtCore.QRect(740, 695, 221, 41))
        self.Me.setObjectName("Me")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Татарский толковый словарь"))
        self.pushButton.setText(_translate("MainWindow", "Найти слово"))
        self.Title.setText(_translate("MainWindow",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                      "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'MS Reference Sans Serif\'; "
                                      "font-size:26pt; font-weight:400;"
                                      "font-style:normal;\">\n"
                                      "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; "
                                      "margin-left:0px; margin-right:0px;"
                                      "-qt-block-indent:0; text-indent:0px;\"><span style=\" "
                                      "color:#000000;\">Татарский толковый "
                                      "словарь</span></p></body></html>"))
        self.InfoBox.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Me.setText(_translate("MainWindow", "Автор: Шайхутдинов Абу Бакр Ильгамович"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
